services:
  authelia:
    image: authelia/authelia:4
    container_name: authelia
    restart: unless-stopped
    volumes:
      - ./config:/config
    secrets:
      - jwt_secret
      - session_secret
      - storage_encryption_key
    environment:
      TZ: Europe/Zurich
      PUID: 10002
      PGID: 10002
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/storage_encryption_key
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.wenger.dev`)
      - traefik.http.routers.authelia.entryPoints=https
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.tls.certresolver=cloudflare
      - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth
      - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name

secrets:
  jwt_secret:
    environment: JWT_SECRET
  session_secret:
    environment: SESSION_SECRET
  storage_encryption_key:
    environment: STORAGE_ENCRYPTION_KEY

networks:
  default:
    external: true
    name: private
