---
###############################################################
#                   Authelia configuration                    #
###############################################################

theme: "auto"

server:
  endpoints:
    authz:
      forward-auth:
        implementation: "ForwardAuth"

log:
  level: "info"

authentication_backend:
  file:
    path: "/config/users.yml"

access_control:
  default_policy: "deny"
  rules:
    - domain: "traefik.home.wenger.dev"
      policy: "one_factor"
    - domain: "cam01.wenger.dev"
      policy: "one_factor"
    - domain: "cam02.wenger.dev"
      policy: "one_factor"
    - domain: "cam03.wenger.dev"
      policy: "one_factor"

session:
  cookies:
    - domain: "wenger.dev"
      authelia_url: "https://auth.wenger.dev"
      expiration: "3 hour"
      inactivity: "15 minutes"
      default_redirection_url: "https://wenger.dev"

regulation:
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"

storage:
  local:
    path: "/config/db.sqlite3"

notifier:
  filesystem:
    filename: "/config/notification.txt"
